<a href="https://colab.research.google.com/github/Moorehe2/AHIARDIS/blob/main/Copy_of_AM_JUPYTERNOTEBOOK1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd





df1 = pd.read_csv('Indicators_of_Anxiety_or_Depression_Based_on_Reported_Frequency_of_Symptoms_During_Last_7_Days.csv')
df1

                                              Indicator  ... Quartile Range
0                       Symptoms of Depressive Disorder  ...            NaN
1                       Symptoms of Depressive Disorder  ...            NaN
2                       Symptoms of Depressive Disorder  ...            NaN
3                       Symptoms of Depressive Disorder  ...            NaN
4                       Symptoms of Depressive Disorder  ...            NaN
...                                                 ...  ...            ...
7132  Symptoms of Anxiety Disorder or Depressive Dis...  ...      21.6-26.2
7133  Symptoms of Anxiety Disorder or Depressive Dis...  ...      28.2-31.2
7134  Symptoms of Anxiety Disorder or Depressive Dis...  ...      31.3-37.5
7135  Symptoms of Anxiety Disorder or Depressive Dis...  ...      21.6-26.2
7136  Symptoms of Anxiety Disorder or Depressive Dis...  ...      26.3-28.1

[7137 rows x 14 columns]

In [ ]:
import pandas as pd

df2 = pd.read_csv('Hospitalization_Discharge_Rates.csv')
df2

    OBJECTID    ZIP  Anxiety_Di  ...  Total_ACSC   SHAPE_Length    SHAPE_Area
0          1  60002  393.608997  ...           0  215525.155184  1.149062e+09
1          2  60010  132.835014  ...           0  178637.109618  8.027354e+08
2          3  60015  142.476163  ...           0  111400.890558  3.674576e+08
3          4  60020  201.704730  ...           0   92363.084625  1.666177e+08
4          5  60030  261.648844  ...           0  247258.224672  8.455179e+08
5          6  60031  240.857947  ...           0  163995.181561  5.271176e+08
6          7  60035  129.593011  ...           0  115796.723820  3.457929e+08
7          8  60040  123.456790  ...           0   25907.372467  1.780943e+07
8          9  60042  261.025401  ...           0   45385.395226  4.517757e+07
9         10  60044  182.450343  ...           0   92539.708731  2.127777e+08
10        11  60045  173.848054  ...           0  161457.245301  6.214754e+08
11        12  60046  321.294357  ...           0  207743.912574  7.304244e+08
12        13  60047  187.110680  ...           0  176981.859420  9.193818e+08
13        14  60048  175.294814  ...           0  196071.573674  8.190083e+08
14        15  60060  223.996627  ...           0  180171.962436  6.175913e+08
15        16  60061  169.573643  ...           0  102713.138127  2.574212e+08
16        17  60064  530.465048  ...           0   90452.895586  1.399011e+08
17        18  60069  108.420672  ...           0  146555.427438  1.700669e+08
18        19  60073  300.694331  ...           0  209118.936758  5.196587e+08
19        20  60083  260.065498  ...           0  164753.217612  7.282379e+08
20        21  60084  268.901914  ...           0  159182.367883  5.051635e+08
21        22  60085  509.524881  ...           0  137038.947754  3.919074e+08
22        23  60087  436.035489  ...           0  163122.611793  3.898800e+08
23        24  60089  169.135565  ...           0  164174.744392  2.277724e+08
24        25  60096  294.259527  ...           0   62444.471661  1.413737e+08
25        26  60099  461.371925  ...           0  188925.390246  6.262642e+08

[26 rows x 15 columns]

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd 
from pandas.io.json import json_normalize
import json